version: '3'
services:
  psql:
    image: postgres:latest
    environment:
      POSTGRES_DB: nats_streaming_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cg5513

  app:
    build: .
    ports:
      - "9013:9013"
    depends_on:
      - psql
